In [ ]:
import pandas as pd
import numpy as np
import pprint


#pandasのバージョンを確認

print(pd.__version__)

1.0.5


In [ ]:
#Python本体や依存パッケージのバージョン、OSの種類などを含む詳細な情報

pd.show_versions()

In [ ]:
#例としてタイタニックの生存者のデータを使用する。
#https://www.kaggle.com/c/titanic

df = pd.read_csv('data/src/titanic_train.csv')

print(df.head())
print("\n")

df.info()

print(len(df))
print("\n")

print(len(df.columns))
print("\n")

print(df.shape)
print("\n")
print(df.shape[0])
print("\n")
print(df.shape[1])
print("\n")

row, col = df.shape
print(row)
print("\n")
print(col)
print("\n")

print(df.size)
print("\n")
print(df.shape[0] * df.shape[1])
print("\n")


#set_index()メソッドでデータ列をインデックスとして指定すると、その列はデータ本体（values属性）から取り除かれるので、列数にカウントされない。
df_multiindex = df.set_index(['Sex', 'Pclass', 'Embarked', 'PassengerId'])
print(len(df_multiindex))
print("\n")
print(len(df_multiindex.columns))
print("\n")
print(df_multiindex.shape)
print("\n")
print(df_multiindex.size)
print("\n")



s = df['PassengerId']
print(s.head())
print("\n")

#pandas.Seriesは一次元なので、len()でもsize属性でも全要素数（サイズ）が取得できる。
print(len(s))
print("\n")
print(s.size)
print("\n")
print(s.shape)
print("\n")

#pandas.Seriesにはinfo()メソッドは無い。


In [ ]:
#pandas.Seriesは一つのデータ型dtype、panas.DataFrameは各列ごとにそれぞれデータ型dtypeを保持している。



データ型dtype 型コード	説明\
int8	i1	符号あり8ビット整数型\
int16	i2	符号あり16ビット整数型\
int32	i4	符号あり32ビット整数型\
int64	i8	符号あり64ビット整数型\
uint8	u1	符号なし8ビット整数型\
uint16	u2	符号なし16ビット整数型\
uint32	u4	符号なし32ビット整数型\
uint64	u8	符号なし64ビット整数型\
float16	f2	半精度浮動小数点型（符号部1ビット、指数部5ビット、仮数部10ビット）\
float32	f4	単精度浮動小数点型（符号部1ビット、指数部8ビット、仮数部23ビット）\
float64	f8	倍精度浮動小数点型（符号部1ビット、指数部11ビット、仮数部52ビット）\
float128	f16	四倍精度浮動小数点型（符号部1ビット、指数部15ビット、仮数部112ビット）\
complex64	c8	複素数（実部・虚部がそれぞれfloat32）\
complex128	c16	複素数（実部・虚部がそれぞれfloat64）\
complex256	c32	複素数（実部・虚部がそれぞれfloat128）\
bool	?	ブール型（True or False）\
object	O	Pythonオブジェクト型\

データ型名の末尾の数字はbitで表し、型コード末尾の数字はbyteで表す。

In [ ]:
s = pd.Series([0, 1, 2], dtype=np.float64)
print(s.dtype)
print("\n")

s = pd.Series([0, 1, 2], dtype='float64')
print(s.dtype)
print("\n")

s = pd.Series([0, 1, 2], dtype='f8')
print(s.dtype)
print("\n")


float64
float64
float64


In [ ]:
s = pd.Series([0, 1, 2], dtype='float')
print(s.dtype)
print("\n")

s = pd.Series([0, 1, 2], dtype=float)
print(s.dtype)
print("\n")

s = pd.Series([0, 1, 2], dtype='uint')
print(s.dtype)

float64
float64
uint64


In [ ]:
print(np.iinfo(1))
print("\n")
print(np.finfo(1.0))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



In [ ]:
s_object = pd.Series([0, 0.1, 'abc', pd.np.nan])
print(s_object)
print("\n")

print(s_object.map(type))

0      0
1    0.1
2    abc
3    NaN
dtype: object
0      <class 'int'>
1    <class 'float'>
2      <class 'str'>
3    <class 'float'>
dtype: object


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.


In [ ]:
s_str_constructor = pd.Series([0, 0.1, 'abc', pd.np.nan], dtype=str)
print(s_str_constructor)
print("\n")

print(s_str_constructor.map(type))

0      0
1    0.1
2    abc
3    NaN
dtype: object
0      <class 'str'>
1      <class 'str'>
2      <class 'str'>
3    <class 'float'>
dtype: object


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.


In [ ]:
s_str_astype = s_object.astype(str)
print(s_str_astype)
print("\n")

print(s_str_astype.map(type))

0      0
1    0.1
2    abc
3    nan
dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
dtype: object


In [ ]:
print(s_str_astype.str.len())
print("\n")

print(s_object.str.len())

0    1
1    3
2    3
3    3
dtype: int64
0    NaN
1    NaN
2    3.0
3    NaN
dtype: float64


In [ ]:
print(s_object.astype(str).str.len())


0    1
1    3
2    3
3    3
dtype: int64


In [ ]:
print(s_object)
print("\n")

print(s_object.map(type))

0      0
1    0.1
2    abc
3    NaN
dtype: object
0      <class 'int'>
1    <class 'float'>
2      <class 'str'>
3    <class 'float'>
dtype: object


In [ ]:
print(s_object.isnull())
print("\n")

print(s_object.dropna())

0    False
1    False
2    False
3     True
dtype: bool
0      0
1    0.1
2    abc
dtype: object


In [ ]:
print(s_str_astype)
print("\n")

print(s_str_astype.map(type))

0      0
1    0.1
2    abc
3    nan
dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
dtype: object


In [ ]:
print(s_str_astype.isnull())
print("\n")

print(s_str_astype.dropna())

0    False
1    False
2    False
3    False
dtype: bool
0      0
1    0.1
2    abc
3    nan
dtype: object


In [ ]:
s_str_astype_nan = s_str_astype.replace('nan', pd.np.nan)
print(s_str_astype_nan)
print("\n")

print(s_str_astype_nan.map(type))
print("\n")

print(s_str_astype_nan.isnull())

0      0
1    0.1
2    abc
3    NaN
dtype: object
0      <class 'str'>
1      <class 'str'>
2      <class 'str'>
3    <class 'float'>
dtype: object
0    False
1    False
2    False
3     True
dtype: bool


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.


In [ ]:
df = pd.read_csv('sample_header.csv')
print(df)
print("\n")

print(df.dtypes)
print("\n")


#print(df.map(type))



s = df['c']
print(s)

    a   b   c   d
0  11  12  13  14
1  21  22  23  24
2  31  32  33  34


a    int64
b    int64
c    int64
d    int64
dtype: object


0    13
1    23
2    33
Name: c, dtype: int64


In [ ]:
s_f = s.astype('float64')
print(s_f)
print("\n")

print(s)
print("\n")

s_f = s.astype('float')
print(s_f.dtype)
print("\n")

s_f = s.astype(float)
print(s_f.dtype)
print("\n")

s_f = s.astype('f8')
print(s_f.dtype)


A    0.0
B    1.0
C    2.0
D    3.0
Name: sample, dtype: float64


A    0.0
B    1.0
C    2.0
D    3.0
Name: sample, dtype: float64


float64


float64


float64


In [ ]:
s_s = s.astype(str)
print(s_s)
print("\n")

print(s_s.map(type))
print("\n")

s_o = s.astype('object')
print(s_o)
print("\n")

print(s_o.map(type))


#print(s_o.applymap(type)) <- 'Series' object has no attribute 'applymap'


0    13
1    23
2    33
Name: c, dtype: object


0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
Name: c, dtype: object


0    13
1    23
2    33
Name: c, dtype: object


0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
Name: c, dtype: object


In [ ]:
df_f = df.astype('float64')
print(df_f)
print("\n")

print(df_f.dtypes)

      a     b     c     d
0  11.0  12.0  13.0  14.0
1  21.0  22.0  23.0  24.0
2  31.0  32.0  33.0  34.0


a    float64
b    float64
c    float64
d    float64
dtype: object


In [ ]:
df_fcol = df.astype({'a': float})
print(df_fcol)
print("\n")

print(df_fcol.dtypes)
print("\n")

df_fcol2 = df.astype({'a': 'float32', 'c': 'int8'})
print(df_fcol2)
print("\n")

print(df_fcol2.dtypes)

      a   b   c   d
0  11.0  12  13  14
1  21.0  22  23  24
2  31.0  32  33  34


a    float64
b      int64
c      int64
d      int64
dtype: object


      a   b   c   d
0  11.0  12  13  14
1  21.0  22  23  24
2  31.0  32  33  34


a    float32
b      int64
c       int8
d      int64
dtype: object


In [ ]:
df = pd.read_csv('sample_header_index_dtype.csv', index_col=0)
print(df)
print("\n")

print(df.dtypes)
print("\n")

print(df.applymap(type))
print("\n")

#print(df.map(type)) <- 'DataFrame' object has no attribute 'map'


print(df.apply(type))
print("\n")


       a    b      c  d
ONE    1    1  100.0  x
TWO    2   20    NaN  y
THREE  3  300  300.0  z


a      int64
b      int64
c    float64
d     object
dtype: object


                   a              b                c              d
ONE    <class 'int'>  <class 'int'>  <class 'float'>  <class 'str'>
TWO    <class 'int'>  <class 'int'>  <class 'float'>  <class 'str'>
THREE  <class 'int'>  <class 'int'>  <class 'float'>  <class 'str'>


a    <class 'pandas.core.series.Series'>
b    <class 'pandas.core.series.Series'>
c    <class 'pandas.core.series.Series'>
d    <class 'pandas.core.series.Series'>
dtype: object




In [ ]:


df_str = pd.read_csv('sample_header_index_dtype.csv',
                     index_col=0, dtype=str)
print(df_str)
print("\n")

print(df_str.dtypes)
print("\n")

print(df_str.applymap(type))

       a    b    c  d
ONE    1  001  100  x
TWO    2  020  NaN  y
THREE  3  300  300  z


a    object
b    object
c    object
d    object
dtype: object


                   a              b                c              d
ONE    <class 'str'>  <class 'str'>    <class 'str'>  <class 'str'>
TWO    <class 'str'>  <class 'str'>  <class 'float'>  <class 'str'>
THREE  <class 'str'>  <class 'str'>    <class 'str'>  <class 'str'>


In [ ]:
df_object = pd.read_csv('sample_header_index_dtype.csv',
                        index_col=0, dtype=object)
print(df_object)
print("\n")

print(df_object.dtypes)
print("\n")

print(df_object.applymap(type))

       a    b    c  d
ONE    1  001  100  x
TWO    2  020  NaN  y
THREE  3  300  300  z


a    object
b    object
c    object
d    object
dtype: object


                   a              b                c              d
ONE    <class 'str'>  <class 'str'>    <class 'str'>  <class 'str'>
TWO    <class 'str'>  <class 'str'>  <class 'float'>  <class 'str'>
THREE  <class 'str'>  <class 'str'>    <class 'str'>  <class 'str'>


In [ ]:
print(df.astype(str).applymap(type))

                   a              b              c              d
ONE    <class 'str'>  <class 'str'>  <class 'str'>  <class 'str'>
TWO    <class 'str'>  <class 'str'>  <class 'str'>  <class 'str'>
THREE  <class 'str'>  <class 'str'>  <class 'str'>  <class 'str'>


In [ ]:
df_col = pd.read_csv('sample_header_index_dtype.csv',
                     index_col=0, dtype={'a': float, 'b': str})
print(df_col)
print("\n")

print(df_col.dtypes)
print("\n")

df_col = pd.read_csv('sample_header_index_dtype.csv',
                     index_col=0, dtype={1: float, 2: str})
print(df_col)
print("\n")

print(df_col.dtypes)

         a    b      c  d
ONE    1.0  001  100.0  x
TWO    2.0  020    NaN  y
THREE  3.0  300  300.0  z


a    float64
b     object
c    float64
d     object
dtype: object


         a    b      c  d
ONE    1.0  001  100.0  x
TWO    2.0  020    NaN  y
THREE  3.0  300  300.0  z


a    float64
b     object
c    float64
d     object
dtype: object


In [ ]:
df_mix = pd.DataFrame({'col_int': [0, 1, 2], 'col_float': [0.1, 0.2, 0.3]}, index=['A', 'B', 'C'])
print(df_mix)
print("\n")

print(df_mix.dtypes)

   col_int  col_float
A        0        0.1
B        1        0.2
C        2        0.3


col_int        int64
col_float    float64
dtype: object


In [ ]:
print(df_mix['col_int'] + df_mix['col_float'])

A    0.1
B    1.2
C    2.3
dtype: float64


In [ ]:
print(df_mix / 2)
print("\n")

print((df_mix / 2).dtypes)

   col_int  col_float
A      0.0       0.05
B      0.5       0.10
C      1.0       0.15


col_int      float64
col_float    float64
dtype: object


In [ ]:
print(df_mix * 1)
print("\n")

print((df_mix * 1).dtypes)
print("\n")

print(df_mix * 1.0)
print("\n")

print((df_mix * 1.0).dtypes)

   col_int  col_float
A        0        0.1
B        1        0.2
C        2        0.3


col_int        int64
col_float    float64
dtype: object


   col_int  col_float
A      0.0        0.1
B      1.0        0.2
C      2.0        0.3


col_int      float64
col_float    float64
dtype: object


In [ ]:
print(df_mix.loc['A'])
print("\n")

print(df_mix.T)
print("\n")

print(df_mix.T.dtypes)

col_int      0.0
col_float    0.1
Name: A, dtype: float64


             A    B    C
col_int    0.0  1.0  2.0
col_float  0.1  0.2  0.3


A    float64
B    float64
C    float64
dtype: object


In [ ]:
df_mix.at['A', 'col_int'] = 10.9
df_mix.at['A', 'col_float'] = 10

print(df_mix)
print("\n")

print(df_mix.dtypes)

   col_int  col_float
A       10       10.0
B        1        0.2
C        2        0.3


col_int        int64
col_float    float64
dtype: object


In [ ]:
#列の型に変換できない値を代入しようとするとエラーとなる
df_mix.at['A', 'col_int'] = 'abc'

In [ ]:
print(pd.options.display.max_rows)
print("\n")

pd.options.display.max_rows = 100
print(pd.options.display.max_rows)
print("\n")

print(dir(pd.options))
print("\n")

#pprint.pprint(dir(pd.options.display))
pprint.pprint(dir(pd.options.io.hdf.dropna_table))
print("\n")




100


100


['compute', 'display', 'io', 'mode', 'plotting']


['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'num

In [ ]:
pd.describe_option()

In [ ]:
pd.describe_option("compute")

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]


In [ ]:
pd.describe_option("max_col")

display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 0] [currently: 0]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]


In [ ]:
pd.describe_option('max.*col')

display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 0] [currently: 0]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per col

In [ ]:
#webページの表（tableタグ）のスクレイピング

!pip install lxml html5lib beautifulsoup4

url = 'https://info.finance.yahoo.co.jp/ranking/?kd=4'
dfs = pd.read_html(url)

print(len(dfs))
print("\n")

print(dfs[0].head())


1


  順位   コード    市場             名称    取引値  取引値.1     発行済み株式数 時価総額（百万円） 単元株数  掲示板
0  1  7203  東証1部      トヨタ自動車(株)  15:00   6955  3262997492  22694148  100  掲示板
1  2  9984  東証1部  ソフトバンクグループ(株)  15:00   5800  2089814330  12120923  100  掲示板
2  3  6861  東証1部       (株)キーエンス  15:00  44800   243207684  10895704  100  掲示板
3  4  6758  東証1部         ソニー(株)  15:00   8216  1261058781  10360859  100  掲示板
4  5  9432  東証1部      日本電信電話(株)  15:00   2358  3900788940   9198060  100  掲示板


In [ ]:
print(dfs[1].head())

IndexError: ignored

In [ ]:
print(dfs[0][['名称', '時価総額（百万円）']].head())

              名称 時価総額（百万円）
0      トヨタ自動車(株)  22694148
1  ソフトバンクグループ(株)  12120923
2       (株)キーエンス  10895704
3         ソニー(株)  10360859
4      日本電信電話(株)   9198060


In [ ]:
dfs[0].columns = ['順位', 'コード', '市場', '名称', '時刻', '取引値', '発行済み株式数', '時価総額（百万円）', '単元株数', '掲示板']

print(dfs[0][['名称', '時価総額（百万円）']].head())

              名称 時価総額（百万円）
0      トヨタ自動車(株)  22694148
1  ソフトバンクグループ(株)  12120923
2       (株)キーエンス  10895704
3         ソニー(株)  10360859
4      日本電信電話(株)   9198060


In [ ]:
url = 'https://ja.wikipedia.org/wiki/Python'
dfs = pd.read_html(url)

print(len(dfs))

13


In [ ]:
dfs = pd.read_html(url, match='リリース日')

print(len(dfs))
print("\n")

print(dfs[0])
print("\n")

print(dfs[1])

2


   バージョン    リリース日[32]   サポート期限[33]
0    2.0  2000年10月16日          NaN
1    2.1   2001年4月15日          NaN
2    2.2  2001年12月21日          NaN
3    2.3   2003年7月29日          NaN
4    2.4  2004年11月30日          NaN
5    2.5   2006年9月19日          NaN
6    2.6   2008年10月1日  2013年10月29日
7    2.7    2010年7月4日    2020年1月1日


   バージョン    リリース日[32]  サポート期限[33]
0    3.0   2008年12月3日  2009年1月13日
1    3.1   2009年6月27日   2012年4月9日
2    3.2   2011年2月20日  2016年2月20日
3    3.3   2012年9月29日  2017年9月29日
4    3.4   2014年3月16日  2019年3月18日
5    3.5   2015年9月13日     2020年9月
6    3.6  2016年12月23日    2021年12月
7    3.7   2018年6月27日     2023年6月
8    3.8  2019年10月14日    2024年10月


In [ ]:
dfs = pd.read_html(url, match='リリース日', header=0)

print(len(dfs))
print("\n")

print(dfs[0])
print("\n")

print(dfs[1])
print("\n")


2


   バージョン    リリース日[32]   サポート期限[33]
0    2.0  2000年10月16日          NaN
1    2.1   2001年4月15日          NaN
2    2.2  2001年12月21日          NaN
3    2.3   2003年7月29日          NaN
4    2.4  2004年11月30日          NaN
5    2.5   2006年9月19日          NaN
6    2.6   2008年10月1日  2013年10月29日
7    2.7    2010年7月4日    2020年1月1日


   バージョン    リリース日[32]  サポート期限[33]
0    3.0   2008年12月3日  2009年1月13日
1    3.1   2009年6月27日   2012年4月9日
2    3.2   2011年2月20日  2016年2月20日
3    3.3   2012年9月29日  2017年9月29日
4    3.4   2014年3月16日  2019年3月18日
5    3.5   2015年9月13日     2020年9月
6    3.6  2016年12月23日    2021年12月
7    3.7   2018年6月27日     2023年6月
8    3.8  2019年10月14日    2024年10月




In [ ]:
df = pd.concat([dfs[0], dfs[1]], ignore_index=True).sort_values('リリース日[32]')
print(df)

    バージョン    リリース日[32]   サポート期限[33]
0     2.0  2000年10月16日          NaN
2     2.2  2001年12月21日          NaN
1     2.1   2001年4月15日          NaN
3     2.3   2003年7月29日          NaN
4     2.4  2004年11月30日          NaN
5     2.5   2006年9月19日          NaN
6     2.6   2008年10月1日  2013年10月29日
8     3.0   2008年12月3日   2009年1月13日
9     3.1   2009年6月27日    2012年4月9日
7     2.7    2010年7月4日    2020年1月1日
10    3.2   2011年2月20日   2016年2月20日
11    3.3   2012年9月29日   2017年9月29日
12    3.4   2014年3月16日   2019年3月18日
13    3.5   2015年9月13日      2020年9月
14    3.6  2016年12月23日     2021年12月
15    3.7   2018年6月27日      2023年6月
16    3.8  2019年10月14日     2024年10月


In [ ]:
df.to_csv('pandas_read_html_sample.csv')

In [ ]:
df1 = pd.read_csv('pandas_read_html_sample.csv')
print(df1)

    Unnamed: 0  バージョン    リリース日[32]   サポート期限[33]
0            0    2.0  2000年10月16日          NaN
1            2    2.2  2001年12月21日          NaN
2            1    2.1   2001年4月15日          NaN
3            3    2.3   2003年7月29日          NaN
4            4    2.4  2004年11月30日          NaN
5            5    2.5   2006年9月19日          NaN
6            6    2.6   2008年10月1日  2013年10月29日
7            8    3.0   2008年12月3日   2009年1月13日
8            9    3.1   2009年6月27日    2012年4月9日
9            7    2.7    2010年7月4日    2020年1月1日
10          10    3.2   2011年2月20日   2016年2月20日
11          11    3.3   2012年9月29日   2017年9月29日
12          12    3.4   2014年3月16日   2019年3月18日
13          13    3.5   2015年9月13日      2020年9月
14          14    3.6  2016年12月23日     2021年12月
15          15    3.7   2018年6月27日      2023年6月
16          16    3.8  2019年10月14日     2024年10月


In [ ]:
#pandas.DataFrame, SeriesとNumPy配列ndarrayを相互に変換

df = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], columns=['a', 'b', 'c'])
print(df)
print("\n")

a_df = df.values
print(a_df)
print("\n")

print(type(a_df))
print("\n")

print(a_df.dtype)
print("\n")



   a  b  c
0  1  2  3
1  4  5  6


[[1 2 3]
 [4 5 6]]


<class 'numpy.ndarray'>


int64




In [ ]:
s = df["a"]
print(s)
print("\n")

a_s = s.values
print(a_s)
print("\n")

print(type(a_s))
print("\n")

print(a_s.dtype)

0    1
1    4
Name: a, dtype: int64


[1 4]


<class 'numpy.ndarray'>


int64




In [ ]:
df_f = pd.DataFrame([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print(df_f)
print("\n")

a_df_f = df_f.values
print(a_df_f)
print("\n")

print(type(a_df_f))
print("\n")

print(a_df_f.dtype)

     0    1    2
0  0.1  0.2  0.3
1  0.4  0.5  0.6


[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


<class 'numpy.ndarray'>


float64


In [ ]:
df_multi = pd.read_csv('sample_pandas_normal.csv')
print(df_multi)
print("\n")

a_df_multi = df_multi.values
print(a_df_multi)
print("\n")

print(type(a_df_multi))
print("\n")

print(a_df_multi.dtype)

   Unnamed: 0     name  age state  point
0           0    Alice   24    NY     64
1           1      Bob   42    CA     92
2           2  Charlie   18    CA     70
3           3     Dave   68    TX     70
4           4    Ellen   24    CA     88
5           5    Frank   30    NY     57


[[0 'Alice' 24 'NY' 64]
 [1 'Bob' 42 'CA' 92]
 [2 'Charlie' 18 'CA' 70]
 [3 'Dave' 68 'TX' 70]
 [4 'Ellen' 24 'CA' 88]
 [5 'Frank' 30 'NY' 57]]


<class 'numpy.ndarray'>


object


In [ ]:
a_df_int = df_multi[['age', 'point']].values
print(a_df_int)
print("\n")

print(type(a_df_int))
print(a_df_int.dtype)
print("\n")

#.Tで転置
print(a_df_int.T)


[[24 64]
 [42 92]
 [18 70]
 [68 70]
 [24 88]
 [30 57]]


<class 'numpy.ndarray'>
int64


[[24 42 18 68 24 30]
 [64 92 70 70 88 57]]


In [ ]:
#int64型の列のみ抽出
a_df_int = df_multi.select_dtypes(include=int).values
print(a_df_int)
print("\n")

print(type(a_df_int))
print(a_df_int.dtype)
print("\n")


[[ 0 24 64]
 [ 1 42 92]
 [ 2 18 70]
 [ 3 68 70]
 [ 4 24 88]
 [ 5 30 57]]


<class 'numpy.ndarray'>
int64




In [ ]:
#pandas.Seriesを生成
#コンストラクタに他の引数を何も指定しないと、元のndarrayの型のSeriesとなる

a = np.arange(4)
print(a)
print("\n")

s = pd.Series(a)
print(s)

[0 1 2 3]


0    0
1    1
2    2
3    3
dtype: int64


In [ ]:
index = ['A', 'B', 'C', 'D']
name = 'sample'
s = pd.Series(data=a, index=index, name=name, dtype='float')
print(s)

A    0.0
B    1.0
C    2.0
D    3.0
Name: sample, dtype: float64


In [ ]:
a = np.arange(12).reshape((4, 3))
print(a)
print("\n")
print(type(a))

#s = pd.Series(a) <- Exception: Data must be 1-dimensional
#print(s)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


<class 'numpy.ndarray'>


In [ ]:
s1 = pd.Series(a[2])
print(s1)
print("\n")

s2 = pd.Series(a.T[2])
print(s2)


0    6
1    7
2    8
dtype: int64


0     2
1     5
2     8
3    11
dtype: int64


In [ ]:
a = np.arange(12).reshape((3, 4))
print(a)
print("\n")

df = pd.DataFrame(a)
print(df)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [ ]:
a = np.arange(12).reshape((2, 6))
print(a)
print("\n")

df = pd.DataFrame(a)
print(df)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


   0  1  2  3   4   5
0  0  1  2  3   4   5
1  6  7  8  9  10  11


In [ ]:
a = np.arange(12).reshape((6, 2))
print(a)
print("\n")

df = pd.DataFrame(a)
print(df)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


    0   1
0   0   1
1   2   3
2   4   5
3   6   7
4   8   9
5  10  11


In [ ]:
index = ['A', 'B', 'C', 'D']
columns = ['a', 'b', 'c']
a = np.arange(12).reshape((4, 3))
df = pd.DataFrame(data=a, index=index, columns=columns, dtype='float')
print(df)

     a     b     c
A  0.0   1.0   2.0
B  3.0   4.0   5.0
C  6.0   7.0   8.0
D  9.0  10.0  11.0


In [ ]:
df = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], columns=['a', 'b', 'c'])
print(df)
print("\n")

a_values = df.values
print(a_values)


   a  b  c
0  1  2  3
1  4  5  6


[[1 2 3]
 [4 5 6]]


In [ ]:
#valuesはビューを返し、一方の値を変更するともう一方の値も変更される

print(np.shares_memory(a_values, df))
print("\n")

a_values[0, 0] = 100
print(a_values)
print("\n")

print(df)

True


[[100   2   3]
 [  4   5   6]]


     a  b  c
0  100  2  3
1    4  5  6


In [ ]:
#常にビューを返すわけではなく、例えば各列のデータ型dtypeが異なる場合はコピー

df_if = pd.DataFrame(data=[[1, 0.1], [2, 0.2]], columns=['int', 'float'])
print(df_if)
print("\n")

print(df_if.dtypes)
print("\n")

a_values_if = df_if.values
print(a_values_if)
print("\n")

print(np.shares_memory(a_values_if, df_if))
print("\n")

a_values_if[0, 0] = 100
print(a_values_if)
print("\n")

print(df_if)

   int  float
0    1    0.1
1    2    0.2


int        int64
float    float64
dtype: object


[[1.  0.1]
 [2.  0.2]]


False


[[100.    0.1]
 [  2.    0.2]]


   int  float
0    1    0.1
1    2    0.2


In [ ]:
#行や列などの範囲を指定してvaluesを取得する場合は指定方法によってビューかコピーかが異なったりする

print(df[['a', 'c']].values)
print("\n")

print(np.shares_memory(df[['a', 'c']].values, df))
print("\n")

print(df.iloc[:, ::2].values)
print("\n")

print(np.shares_memory(df.iloc[:, ::2].values, df))

[[100   3]
 [  4   6]]


False


[[100   3]
 [  4   6]]


True


In [ ]:
#ビューだと問題がある場合はvaluesのcopy()で明示的にコピーを生成すればよい

a_values_copy = df.values.copy()
print(a_values_copy)
print("\n")

print(np.shares_memory(a_values_copy, df))
print("\n")

a_values_copy[0, 0] = 10
print(a_values_copy)
print("\n")

print(df)

[[100   2   3]
 [  4   5   6]]


False


[[10  2  3]
 [ 4  5  6]]


     a  b  c
0  100  2  3
1    4  5  6


In [ ]:
#コンストラクタpandas.DataFrame(), pandas.Series()にnumpy.ndarrayを渡すとメモリが共有される。
#一方の値を変更するともう一方の値も変更される

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("\n")

df_a = pd.DataFrame(a, columns=['a', 'b', 'c'])
print(df_a)
print("\n")

print(np.shares_memory(a, df_a))
print("\n")

a[0, 0] = 100
print(a)
print("\n")

print(df_a)
print("\n")

df_a.iat[1, 0] = 10
print(df_a)
print("\n")

print(a)

[[1 2 3]
 [4 5 6]]


   a  b  c
0  1  2  3
1  4  5  6


True


[[100   2   3]
 [  4   5   6]]


     a  b  c
0  100  2  3
1    4  5  6


     a  b  c
0  100  2  3
1   10  5  6


[[100   2   3]
 [ 10   5   6]]


In [ ]:
#メモリを共有させたくない場合はnumpy.ndarrayのcopy()でコピーをコンストラクタの引数に指定する

df_a_copy = pd.DataFrame(a.copy(), columns=['a', 'b', 'c'])
print(df_a_copy)
print("\n")

a[0, 0] = 1
print(a)
print("\n")

print(df_a_copy)

     a  b  c
0  100  2  3
1   10  5  6


[[ 1  2  3]
 [10  5  6]]


     a  b  c
0  100  2  3
1   10  5  6


In [ ]:
#四捨五入ではなく偶数への丸め

from decimal import Decimal, ROUND_HALF_UP, ROUND_HALF_EVEN
import platform

print(platform.python_version())
print(pd.__version__)
print(np.__version__)
print("\n")

s_f = pd.Series([123.456, 654.123])
print(s_f)
print("\n")

#round()の引数に整数nを渡すと、小数点以下n桁に丸められる。
print(s_f.round())
print("\n")

print(s_f.round().astype(int))


3.6.9
1.0.5
1.18.5


0    123.456
1    654.123
dtype: float64


0    123.0
1    654.0
dtype: float64


0    123
1    654
dtype: int64


In [ ]:
#正の整数は小数点以下の桁数指定、負の整数は整数の桁数指定になる

print(s_f.round(2))
print("\n")

print(s_f.round(-2))

0    123.46
1    654.12
dtype: float64


0    100.0
1    700.0
dtype: float64


In [ ]:
print(round(2.50))

2


In [ ]:
print(round(2.51))

3


In [ ]:
print(round(3.50))

4


In [ ]:
print(round(3.49))

3


In [ ]:
s_i = pd.Series([123, 654])

print(s_i)
print("\n")

print(s_i.round())
print("\n")

print(s_i.round(2))
print("\n")

print(s_i.round(-2))


0    123
1    654
dtype: int64


0    123
1    654
dtype: int64


0    123
1    654
dtype: int64


0    100
1    700
dtype: int64


In [ ]:
#round()メソッドは数値が丸められた新しいオブジェクトを返し、元のオブジェクトは変更されない

s_i_round = s_i.round(-2)

print(s_i_round)
print("\n")

print(s_i)

0    100
1    700
dtype: int64


0    123
1    654
dtype: int64


In [ ]:
df = pd.DataFrame({'f': [123.456, 654.321], 'i': [123, 654], 's': ['abc', 'xyz']})

print(df)
print("\n")

print(df.dtypes)

         f    i    s
0  123.456  123  abc
1  654.321  654  xyz


f    float64
i      int64
s     object
dtype: object


In [ ]:
#round()の引数を省略した場合および整数を指定した場合は全ての列が対応する桁数に丸められる

print(df.round())
print("\n")

print(df.round(2))
print("\n")

print(df.round(-2))

       f    i    s
0  123.0  123  abc
1  654.0  654  xyz


        f    i    s
0  123.46  123  abc
1  654.32  654  xyz


       f    i    s
0  100.0  100  abc
1  700.0  700  xyz


In [ ]:
#キーを列名、値を桁数とする辞書を引数に指定すると、各列に個別に桁数を指定することができる。指定しない列は変化なし

print(df.round({'f': 2, 'i': -1}))
print("\n")

print(df.round({'i': -2}))

        f    i    s
0  123.46  120  abc
1  654.32  650  xyz


         f    i    s
0  123.456  100  abc
1  654.321  700  xyz


$$
p_n = \frac{1}{2}
$$


In [ ]:
#CSVを読み込む
read_csv()

#CSVに出力（保存）
to_csv()

#エクセルファイルを読み込む
read_excel()

#エクセルファイルに出力（保存）
to_excel()

#Json形式を読み込む
read_json()

#Json形式に出力（保存）
to_json()



In [ ]:
import pandas as pd
import numpy as np
import pprint

a = pd.read_csv("sample_header.csv")
print(a)

    a   b   c   d
0  11  12  13  14
1  21  22  23  24
2  31  32  33  34


In [ ]:
import csv
with open(r'sample_header.csv', encoding='utf-8') as f:
  #rows = csv.reader(f)
  rows = [row for row in csv.reader(f)]

rows


[['a', 'b', 'c', 'd'],
 ['11', '12', '13', '14'],
 ['21', '22', '23', '24'],
 ['31', '32', '33', '34']]

In [ ]:
import numpy as np

arr = np.loadtxt(r"sample_header.csv",encoding="utf-8",delimiter=",",skiprows=1)

arr

array([[11., 12., 13., 14.],
       [21., 22., 23., 24.],
       [31., 32., 33., 34.]])

In [ ]:
c = pd.read_json("sample_json.json")
print(c)

                        _id  index
0  5f5a1bb73ea9fdbc823f8758      0
1  5f5a1bb77ed56790b9808b32      1


In [ ]:
type(c)

pandas.core.frame.DataFrame

In [ ]:
c.at[0, "_id"] = 58
c.at[1, "_id"] = 32

print(c)

  _id  index
0  58      0
1  32      1
